version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run: yarn --frozen-lockfile

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: yarn start

workflows:
  version: 2

  test:
    jobs:
      - build

  nightly:
    triggers:
      - schedule:
          # UTC 5:00 AM = EST 12:00 AM daily
          cron: '0 5 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - build
